export const SIGNIN = 'signIn'
export const LOGOUT = 'logout'
export const GET_USER_LOCATIONS = 'getUserLocations'
export const DELETE_USER_LOCATION = 'deleteUserLocations'
export const ADD_USER_LOCATION = 'addUserLocations'
